version: '3.8'

services:
  igrite-bg:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: igrite-bg-app
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount a volume for nginx logs
      - ./logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy with SSL if needed
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   environment:
  #     - DEFAULT_HOST=igrite.bg